// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjU1UcfhvYV7vrCsy6A2XtBN7NMk37TOw',
    appId: '1:67177356854:web:20ad8d641eed65a3fac297',
    messagingSenderId: '67177356854',
    projectId: 'ta-rides2',
    authDomain: 'ta-rides2.firebaseapp.com',
    storageBucket: 'ta-rides2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTcvZTflM7dQ2NfJuITPXR9UCB3pJbEs',
    appId: '1:67177356854:android:f370a172aeea9090fac297',
    messagingSenderId: '67177356854',
    projectId: 'ta-rides2',
    storageBucket: 'ta-rides2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxmgHShXEzsf3zoxqaWRVBMQUftRyUkqk',
    appId: '1:67177356854:ios:e2c9c6dfa46288a6fac297',
    messagingSenderId: '67177356854',
    projectId: 'ta-rides2',
    storageBucket: 'ta-rides2.appspot.com',
    iosBundleId: 'com.example.tarides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxmgHShXEzsf3zoxqaWRVBMQUftRyUkqk',
    appId: '1:67177356854:ios:4c9d8323cd89a572fac297',
    messagingSenderId: '67177356854',
    projectId: 'ta-rides2',
    storageBucket: 'ta-rides2.appspot.com',
    iosBundleId: 'com.example.tarides.RunnerTests',
  );
}
